services:
    btn_message.helper.message:
        class: Btn\MessageBundle\Helper\MessageHelper
        arguments:
            - %btn_message.message_type%

    btn_message.message_manager.default:
        class: Btn\MessageBundle\Model\MessageManager
        arguments:
            - @doctrine.orm.entity_manager
            - %btn_message.message_class%
            - @btn_message.thread_manager
            - @btn_message.helper.message
        calls:
            - [setEventDispacher, ["@event_dispatcher"]]

    btn_message.thread_manager.default:
        class: Btn\MessageBundle\Model\ThreadManager
        arguments:
            - @doctrine.orm.entity_manager
            - %btn_message.thread_class%

    btn_message.message.type:
        class: Btn\MessageBundle\Form\MessageType
        arguments:
            - %btn_message.message_type%

    btn.twig.message_extension:
        class: Btn\MessageBundle\Twig\BtnMessageExtension
        arguments:
            - @btn_message.helper.message
        tags:
            - { name: twig.extension }
